services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    networks:
      - laravel
    depends_on:
      - mysql

  web:
    image: nginx:alpine
    container_name: laravel_web
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - laravel
    depends_on:
      - app

  node:
    image: node:16-alpine
    container_name: laravel_node
    working_dir: /var/www/html
    command: tail -f /dev/null
    volumes:
      - ./:/var/www/html
    networks:
      - laravel

  mysql:
    image: mysql:8.0
    container_name: laravel_mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_ROOT_PASSWORD: ""
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - laravel
    command: --skip-grant-tables

  composer:
    image: composer:2.4.1
    container_name: laravel_composer
    working_dir: /var/www/html
    command: tail -f /dev/null
    volumes:
      - ./:/var/www/html
    networks:
      - laravel

networks:
  laravel:

volumes:
  mysql_data:
